# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63364ac42a7013acdf2ce0d03b786d761a60ba7479102819fe66fe6df900502681c0551e5764d471339e42a96196b3ad2084bf1653256c430772f14c8348a6bf

test:
  secret_key_base: 7d8256952ec45e57be54c41175d7f57ba88d3b7c1f373a2a211a813dc70236271cdff999e4647bbab639b3bcec9d2052601443cc7fe60e57434f966c4f41d88c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
